name: Deploy Integ

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ['integ']
  pull_request:
    branches: ['integ']

jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: [self-hosted, integ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: Set db url
      run: echo "DATABASE_URL=${{ secrets.INTEG_BROALL_DB_URL }}" > .env
    - name: Run diesel
      run: diesel setup
    - run: diesel migration run
    - name: Build release
      run: cargo build --release --verbose
    - name: Restart srvice
      run: sudo systemctl restart broall_rust_back.service
